In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


In [ ]:
path = '/content/drive/MyDrive/Dataset/data.csv'

addding column names from the given text file at : http://kdd.ics.uci.edu/databases/kddcup99/kddcup.names

In [ ]:
header_path = "/content/drive/MyDrive/Dataset/header.txt"
header = []
f = open(header_path, "r")
for i in f:
  p = i.split(',')
  k = p[0].split(':')
  if (k[0])!= 'back':
    header.append(k[0])

Reading the dataset and assigning all the column names and Assigning row index


In [ ]:
data = pd.read_csv(path, names = header)
data = data.reset_index()
del data['index']
data.head()

duration protocol_type  ... dst_host_rerror_rate  dst_host_srv_rerror_rate
0      tcp          http  ...                  0.0                   normal.
1      tcp          http  ...                  0.0                   normal.
2      tcp          http  ...                  0.0                   normal.
3      tcp          http  ...                  0.0                   normal.
4      tcp          http  ...                  0.0                   normal.

[5 rows x 41 columns]

In [ ]:
data.shape

(1048576, 41)

Checking the data types

In [ ]:
data.dtypes

duration                        object
protocol_type                   object
service                         object
flag                             int64
src_bytes                        int64
dst_bytes                        int64
land                             int64
wrong_fragment                   int64
urgent                           int64
hot                              int64
num_failed_logins                int64
logged_in                        int64
num_compromised                  int64
root_shell                       int64
su_attempted                     int64
num_root                         int64
num_file_creations               int64
num_shells                       int64
num_access_files                 int64
num_outbound_cmds                int64
is_host_login                    int64
is_guest_login                   int64
count                            int64
srv_count                      float64
serror_rate                    float64
srv_serror_rate          

Checking the Null Column if any

In [ ]:
data.isnull().sum()

duration                       0
protocol_type                  0
service                        0
flag                           0
src_bytes                      0
dst_bytes                      0
land                           0
wrong_fragment                 0
urgent                         0
hot                            0
num_failed_logins              0
logged_in                      0
num_compromised                0
root_shell                     0
su_attempted                   0
num_root                       0
num_file_creations             0
num_shells                     0
num_access_files               0
num_outbound_cmds              0
is_host_login                  0
is_guest_login                 0
count                          0
srv_count                      0
serror_rate                    0
srv_serror_rate                0
rerror_rate                    0
srv_rerror_rate                0
same_srv_rate                  0
diff_srv_rate                  0
srv_diff_h

In [ ]:
data.head()

duration protocol_type  ... dst_host_rerror_rate  dst_host_srv_rerror_rate
0      tcp          http  ...                  0.0                   normal.
1      tcp          http  ...                  0.0                   normal.
2      tcp          http  ...                  0.0                   normal.
3      tcp          http  ...                  0.0                   normal.
4      tcp          http  ...                  0.0                   normal.

[5 rows x 41 columns]

the 'object' datatype in columns

In [ ]:
for column in data:
  if (data[column].dtype) == 'object':
    print(column)

duration
protocol_type
service
dst_host_srv_rerror_rate


Checking the unique values of object in column

In [ ]:
for column in data:
  if data[column].dtype == 'object':
    print(column, " :",data[column].unique())

duration  : ['tcp' 'udp' 'icmp']
protocol_type  : ['http' 'smtp' 'domain_u' 'auth' 'finger' 'telnet' 'eco_i' 'ftp' 'ntp_u'
 'ecr_i' 'other' 'urp_i' 'private' 'pop_3' 'ftp_data' 'netstat' 'daytime'
 'ssh' 'echo' 'time' 'name' 'whois' 'domain' 'mtp' 'gopher' 'remote_job'
 'rje' 'ctf' 'supdup' 'link' 'systat' 'discard' 'X11' 'shell' 'login'
 'imap4' 'nntp' 'uucp' 'pm_dump' 'IRC' 'Z39_50' 'netbios_dgm' 'ldap'
 'sunrpc' 'courier' 'exec' 'bgp' 'csnet_ns' 'http_443' 'klogin' 'printer'
 'netbios_ssn' 'pop_2' 'nnsp' 'efs' 'hostnames' 'uucp_path' 'sql_net'
 'vmnet' 'iso_tsap' 'netbios_ns' 'kshell' 'urh_i' 'http_2784' 'harvest'
 'aol']
service  : ['SF' 'S2' 'S1' 'S3' 'OTH' 'REJ' 'RSTO' 'S0' 'RSTR' 'RSTOS0' 'SH']
dst_host_srv_rerror_rate  : ['normal.' 'buffer_overflow.' 'loadmodule.' 'perl.' 'neptune.' 'smurf.'
 'guess_passwd.' 'pod.' 'teardrop.' 'portsweep.' 'ipsweep.' 'land.'
 'ftp_write.' 'back.' 'imap.' 'satan.' 'phf.' 'nmap.' 'multihop.'
 'warezmaster.']


Replacing the duration ['tcp', 'udp', 'icmp'] to 0, 1, 2 respectively

In [ ]:
data['duration'].replace({'tcp':0, 'udp':1, 'icmp':2}, inplace = True)
data['duration'].unique()

array([0, 1, 2])

Replacing all the data of protocol type with numeric values (0, 1, 2, .....)

In [ ]:
data['protocol_type'].replace({
    'http':0, 'smtp':1, 'domain_u':2, 'auth':3, 'finger':4, 'telnet':5, 'eco_i':6,
       'ftp':7, 'ntp_u':8, 'ecr_i':9, 'other':10, 'urp_i':11, 'private':12, 'pop_3':13,
       'ftp_data':14, 'netstat':15, 'daytime':16, 'ssh':17, 'echo':18, 'time':19, 'name':20,
       'whois':21, 'domain':22, 'mtp':23, 'gopher':24, 'remote_job':25, 'rje':26, 'ctf':27,
       'supdup':28, 'link':29, 'systat':30, 'discard':31, 'X11':32, 'shell':33, 'login':34,
       'imap4':35, 'nntp':36, 'uucp':37, 'pm_dump':38, 'IRC':39, 'Z39_50':40, 'netbios_dgm':41,
       'ldap':42, 'sunrpc':43, 'courier':44, 'exec':45, 'bgp':46, 'csnet_ns':47, 'http_443':48,
       'klogin':49, 'printer':50, 'netbios_ssn':51, 'pop_2':52,'efs':53,
       'hostnames':54, 'uucp_path':55, 'sql_net':56, 'vmnet':57, 'iso_tsap':58,
       'netbios_ns':59, 'kshell':60, 'urh_i':61, 'http_2784':62, 'harvest':63, 'aol':64, 'nnsp':65,
}, inplace = True)

In [ ]:
data['protocol_type'].unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 65, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64])

In [ ]:
data['service'].replace({'SF':0, 'S2':1, 'S1':2, 'S3':3, 'OTH':4, 'REJ':5, 'RSTO':6, 'S0':7, 'RSTR':8,
       'RSTOS0':9, 'SH':10}, inplace = True)

In [ ]:
data['service'].unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Basically there are 4 types of Attacks in the dataset mentioned, **DoS** (back, land, neptune, pod, smurf and teardrop), **Probe** (ipsweep, nmap, portsweep and satan), **Root to Local (R2L)** (ftp write, guess passwd, imap, multihop, phf, spy, warezclient and warezmaster) and **User to Root (U2R)** (buffer overflow, loadmodule, perl and rootkit)

Now as we have to detect whether the connection is "bad" connection or "good" connections we will be replacing all the **'normal' connections as 0 and rest all as 1 (as all of them are different types of attacks)**

In [ ]:
data['dst_host_srv_rerror_rate'].unique()

array(['normal.', 'buffer_overflow.', 'loadmodule.', 'perl.', 'neptune.',
       'smurf.', 'guess_passwd.', 'pod.', 'teardrop.', 'portsweep.',
       'ipsweep.', 'land.', 'ftp_write.', 'back.', 'imap.', 'satan.',
       'phf.', 'nmap.', 'multihop.', 'warezmaster.'], dtype=object)

In [ ]:
data['dst_host_srv_rerror_rate'].replace({'normal.':0}, inplace = True)

In [ ]:
data['dst_host_srv_rerror_rate'].unique()

array([0, 'buffer_overflow.', 'loadmodule.', 'perl.', 'neptune.',
       'smurf.', 'guess_passwd.', 'pod.', 'teardrop.', 'portsweep.',
       'ipsweep.', 'land.', 'ftp_write.', 'back.', 'imap.', 'satan.',
       'phf.', 'nmap.', 'multihop.', 'warezmaster.'], dtype=object)

In [ ]:
data['dst_host_srv_rerror_rate'].replace(['smurf.', 'normal.', 'guess_passwd.', 'pod.', 'teardrop.',
       'portsweep.', 'ipsweep.', 'land.', 'ftp_write.', 'back.', 'imap.',
       'buffer_overflow.', 'satan.', 'phf.', 'nmap.', 'multihop.',
       'neptune.', 'warezmaster.', 'loadmodule.', 'perl.'], 1, inplace = True)

In [ ]:
data['dst_host_srv_rerror_rate'].unique()

array([0, 1])

In [ ]:
data.dtypes

duration                         int64
protocol_type                    int64
service                          int64
flag                             int64
src_bytes                        int64
dst_bytes                        int64
land                             int64
wrong_fragment                   int64
urgent                           int64
hot                              int64
num_failed_logins                int64
logged_in                        int64
num_compromised                  int64
root_shell                       int64
su_attempted                     int64
num_root                         int64
num_file_creations               int64
num_shells                       int64
num_access_files                 int64
num_outbound_cmds                int64
is_host_login                    int64
is_guest_login                   int64
count                            int64
srv_count                      float64
serror_rate                    float64
srv_serror_rate          

Finding duplicate rows and eliminating them

In [ ]:
duplicate_data = data[data.duplicated()] 
print("The total Duplicate Rows are: ", len(duplicate_data))
duplicate_data.head()

The total Duplicate Rows are:  434446


duration  protocol_type  ...  dst_host_rerror_rate  dst_host_srv_rerror_rate
1769         0              0  ...                   0.0                         0
1770         0              0  ...                   0.0                         0
1771         0              0  ...                   0.0                         0
1881         0              0  ...                   0.0                         0
1882         0              0  ...                   0.0                         0

[5 rows x 41 columns]

replacing all the only original data's to the data(variable)  and removing all  the duplicate rows from it

In [ ]:
data = data[~(data.duplicated())]
print("The shape of original data after removing Duplicates", data.shape)

The shape of original data after removing Duplicates (614130, 41)


In [ ]:
data.head()

duration  protocol_type  ...  dst_host_rerror_rate  dst_host_srv_rerror_rate
0         0              0  ...                   0.0                         0
1         0              0  ...                   0.0                         0
2         0              0  ...                   0.0                         0
3         0              0  ...                   0.0                         0
4         0              0  ...                   0.0                         0

[5 rows x 41 columns]

In [ ]:
data.describe()

duration  ...  dst_host_srv_rerror_rate
count  614130.000000  ...             614130.000000
mean        0.064188  ...                  0.089729
std         0.277083  ...                  0.285793
min         0.000000  ...                  0.000000
25%         0.000000  ...                  0.000000
50%         0.000000  ...                  0.000000
75%         0.000000  ...                  0.000000
max         2.000000  ...                  1.000000

[8 rows x 41 columns]

Printing the correlation of independent variable on dependent variable and segregating only those column which is positevely correlated to the dependent variable here('dst_host_srv_rerror_rate')

In [ ]:
k = []
for each_column in data:
  if each_column != 'dst_host_srv_rerror_rate' and np.corrcoef(data[each_column], data['dst_host_srv_rerror_rate'])[0][1] > 0 :
    k.append(each_column)
    print("Correlation of ", each_column, "with dst_host_srv_rerror_rate", np.corrcoef(data[each_column], data['dst_host_srv_rerror_rate'])[0][1])

Correlation of  duration with dst_host_srv_rerror_rate 0.10159812131976625
Correlation of  protocol_type with dst_host_srv_rerror_rate 0.6808263998659685
Correlation of  service with dst_host_srv_rerror_rate 0.877880858483367
Correlation of  flag with dst_host_srv_rerror_rate 0.003917197840835321
Correlation of  dst_bytes with dst_host_srv_rerror_rate 0.015741310612688266
Correlation of  land with dst_host_srv_rerror_rate 0.06039951119700783
Correlation of  wrong_fragment with dst_host_srv_rerror_rate 0.0007463828570370416
Correlation of  hot with dst_host_srv_rerror_rate 0.014304480875084551
Correlation of  is_guest_login with dst_host_srv_rerror_rate 0.798686504316409


/usr/local/lib/python3.7/dist-packages/numpy/lib/function_base.py:2559: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/usr/local/lib/python3.7/dist-packages/numpy/lib/function_base.py:2560: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]


Correlation of  count with dst_host_srv_rerror_rate 0.05956528115919552
Correlation of  srv_count with dst_host_srv_rerror_rate 0.9198585380402431
Correlation of  serror_rate with dst_host_srv_rerror_rate 0.9211263945562371
Correlation of  srv_serror_rate with dst_host_srv_rerror_rate 0.026953565011537707
Correlation of  rerror_rate with dst_host_srv_rerror_rate 0.023551797534919462
Correlation of  same_srv_rate with dst_host_srv_rerror_rate 0.23986330285623972
Correlation of  srv_diff_host_rate with dst_host_srv_rerror_rate 0.2976020942806076
Correlation of  dst_host_same_srv_rate with dst_host_srv_rerror_rate 0.33180598155094265
Correlation of  dst_host_diff_srv_rate with dst_host_srv_rerror_rate 0.013589260860576631
Correlation of  dst_host_same_src_port_rate with dst_host_srv_rerror_rate 0.00333591687155193
Correlation of  dst_host_srv_diff_host_rate with dst_host_srv_rerror_rate 0.9202142462293307
Correlation of  dst_host_serror_rate with dst_host_srv_rerror_rate 0.924255740988926

Finding corelation of each feature vector with the others and as well as the correlation of that feature vector with the dependent variable.

if the the correlation of one column on other is greater than 95% and if that column' dependency on dependent variable (here 'dst_host_srv_rerror_rate') is high than printing that column

Multi COllinearity Check 

In [ ]:
for i in data:
  for j in data:
    if i != j and (np.corrcoef(data[j], data[i])[0][1])> 0.95 and (np.corrcoef(data[j], data['dst_host_srv_rerror_rate'])[0][1])> 0.90 and (i != 'dst_host_srv_rerror_rate' or j != 'dst_host_srv_rerror_rate'):
      print("Correlation of ", i, "and",  j)
      print(np.corrcoef(data[j], data[i])[0][1])

/usr/local/lib/python3.7/dist-packages/numpy/lib/function_base.py:2559: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/usr/local/lib/python3.7/dist-packages/numpy/lib/function_base.py:2560: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]


Correlation of  srv_count and serror_rate
0.9963552302080522
Correlation of  srv_count and dst_host_srv_diff_host_rate
0.9940140421855699
Correlation of  srv_count and dst_host_serror_rate
0.9937623359969286
Correlation of  serror_rate and srv_count
0.9963552302080521
Correlation of  serror_rate and dst_host_srv_diff_host_rate
0.9913714919845326
Correlation of  serror_rate and dst_host_serror_rate
0.9962107401692143
Correlation of  dst_host_srv_diff_host_rate and srv_count
0.9940140421855698
Correlation of  dst_host_srv_diff_host_rate and serror_rate
0.9913714919845326
Correlation of  dst_host_srv_diff_host_rate and dst_host_serror_rate
0.9938698378096278
Correlation of  dst_host_serror_rate and srv_count
0.9937623359969286
Correlation of  dst_host_serror_rate and serror_rate
0.9962107401692143
Correlation of  dst_host_serror_rate and dst_host_srv_diff_host_rate
0.9938698378096278


We can see that correlation of some column on other is very very high, hence we can take only one column out of it



Now removing the srv_count from our data because it has maximum dependency on  most of the columns.

In [ ]:
k.pop(k.index('srv_count'))
k

['duration',
 'protocol_type',
 'service',
 'flag',
 'dst_bytes',
 'land',
 'wrong_fragment',
 'hot',
 'is_guest_login',
 'count',
 'serror_rate',
 'srv_serror_rate',
 'rerror_rate',
 'same_srv_rate',
 'srv_diff_host_rate',
 'dst_host_same_srv_rate',
 'dst_host_diff_srv_rate',
 'dst_host_same_src_port_rate',
 'dst_host_srv_diff_host_rate',
 'dst_host_serror_rate',
 'dst_host_srv_serror_rate',
 'dst_host_rerror_rate']

Scaling the DAta so that computation power is so less

In [ ]:
from sklearn import preprocessing
scaler = preprocessing.MinMaxScaler()
scaling_columns = k
data[scaling_columns] = scaler.fit_transform(data[scaling_columns])

In [ ]:
data.head()

duration  protocol_type  ...  dst_host_rerror_rate  dst_host_srv_rerror_rate
0       0.0            0.0  ...                   0.0                         0
1       0.0            0.0  ...                   0.0                         0
2       0.0            0.0  ...                   0.0                         0
3       0.0            0.0  ...                   0.0                         0
4       0.0            0.0  ...                   0.0                         0

[5 rows x 41 columns]

From the dataset column i am removing those columns which are not in k and will pass it to training set for training our model

In [ ]:
dropping_columns = []
for i in data:
  if i not in k:
    dropping_columns.append(i)
dropping_columns

['src_bytes',
 'urgent',
 'num_failed_logins',
 'logged_in',
 'num_compromised',
 'root_shell',
 'su_attempted',
 'num_root',
 'num_file_creations',
 'num_shells',
 'num_access_files',
 'num_outbound_cmds',
 'is_host_login',
 'srv_count',
 'srv_rerror_rate',
 'diff_srv_rate',
 'dst_host_count',
 'dst_host_srv_count',
 'dst_host_srv_rerror_rate']

Splitting X and y Dataset to train our model, and assigning only those column to X which are in k and the output variable y to dst_host_srv_rerror_rate

In [ ]:
X = data.drop(dropping_columns, axis = 1)
y = data['dst_host_srv_rerror_rate']
X.shape

(614130, 22)

Splitting the training and testing model in 80 : 20 ratio for training and testing dataset

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [ ]:
X_train.shape, X_test.shape

((491304, 22), (122826, 22))

Importing tensorflow and keras library to perform Deep Neural Network Architecture

In [ ]:
import tensorflow as tf
from tensorflow import keras

Making a Deep Neural Network with 3 hiddent units and one output unit
I have used RELU activation for all the hidden layers and Sigmoid Activation function in output variable

In [ ]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(22, input_shape = (22, ), activation = 'relu'),
    tf.keras.layers.Dense(11, activation = 'relu'),
    tf.keras.layers.Dense(5, activation = 'relu'),
    tf.keras.layers.Dense(1,activation='sigmoid')
])

model.compile(
    optimizer = 'adam',
    loss = 'binary_crossentropy', 
    metrics = ['accuracy']
)
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 22)                506       
_________________________________________________________________
dense_5 (Dense)              (None, 11)                253       
_________________________________________________________________
dense_6 (Dense)              (None, 5)                 60        
_________________________________________________________________
dense_7 (Dense)              (None, 1)                 6         
Total params: 825
Trainable params: 825
Non-trainable params: 0
_________________________________________________________________


Performing 2 epochs and storing the accuracy and loss in epoch_value

In [ ]:
epochs_value = model.fit(X_train, y_train, epochs=2, batch_size = 10, validation_data = (X_test, y_test))

Epoch 1/2
49131/49131 [==============================] - 116s 2ms/step - loss: 0.0248 - accuracy: 0.9959 - val_loss: 0.0076 - val_accuracy: 0.9982
Epoch 2/2
49131/49131 [==============================] - 115s 2ms/step - loss: 0.0075 - accuracy: 0.9980 - val_loss: 0.0059 - val_accuracy: 0.9982


In [ ]:
predicted_value = model.predict(X_test)
predicted_value[:5]

array([[1.9874140e-03],
       [1.0000000e+00],
       [2.2214593e-04],
       [1.0086595e-04],
       [2.0514807e-04]], dtype=float32)

Converting the predicted value to either 0 or 1 based on if the value is > 0.5 else 1 respectively and storing it in y_predict list

In [ ]:
y_predict = []
for i in range(len(predicted_value)):
  if predicted_value[i] < 0.5:
    y_predict.append(0)
  else:
    y_predict.append(1)



Seeing the first 5 predicted values and actual values

In [ ]:
y_predict[:5], y_test[:5]

([0, 1, 0, 0, 0], 733966    0
 551394    1
 143135    0
 810656    0
 241938    0
 Name: dst_host_srv_rerror_rate, dtype: int64)

In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
print("Classification Report: ")
print(classification_report(y_test, y_predict))

Classification Report: 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    111761
           1       0.99      0.99      0.99     11065

    accuracy                           1.00    122826
   macro avg       1.00      0.99      0.99    122826
weighted avg       1.00      1.00      1.00    122826



In [ ]:
print("Confusion Matrix: ")
print(confusion_matrix(y_test, y_predict))

Confusion Matrix: 
[[111690     71]
 [   146  10919]]
